create table clients (
    id int primary key generated by default as identity,
    short_name varchar(100) unique,
    full_name varchar(100),
    inn varchar(11) unique ,
    kpp varchar(10),
    ogrn varchar(14) unique,
    type varchar(10),
    created_at date,
    updated_at timestamp,
    user_id int,
    bank_id int
)