create table users
(
    id            int primary key generated by default as identity,
    name          varchar(100),
    surname       varchar(100),
    patronymic    varchar(100),
    email         varchar(100) unique,
    created_at    date,
    date_of_birth date
)