create table banks
(
    id   int primary key generated by default as identity,
    name varchar(100),
    bik  varchar(10) unique,
    checking_account varchar(21) unique,
    corporate_account varchar(21),
    city varchar(100),
    country varchar(100),
    client_id int,
    created_at date,
    updated_at timestamp
)
