create table products
(
    id         int primary key generated by default as identity,
    name       varchar(100) unique,
    type       varchar(20),
    quantity   int,
    created_at timestamp,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100),
    price      decimal

);

create table products_orders
(
    id         int primary key generated by default as identity,
    product_id int references products (id) on delete cascade,
    order_id   int,
    quantity   int,
    created_at timestamp,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100)
)