create table clients
(
    id         int primary key generated by default as identity,
    short_name varchar(100) unique,
    full_name  varchar(100),
    inn        varchar(11) unique,
    kpp        varchar(10),
    ogrn       varchar(14) unique,
    type       varchar(10),
    created_at timestamp,
    updated_at timestamp,
    created_by varchar(100),
    updated_by varchar(100)
);

create table banks
(
    id                int primary key generated by default as identity,
    name              varchar(100),
    bik               varchar(10),
    checking_account  varchar(21) unique,
    corporate_account varchar(21),
    city              varchar(100),
    country           varchar(100),
    client_id         int references clients (id) on delete cascade,
    created_at        timestamp,
    updated_at        timestamp,
    created_by        varchar(100),
    updated_by        varchar(100)
);

insert into clients(short_name)
values ('Пустой')