create table orders
(
    id                int primary key generated by default as identity,
    client_short_name varchar,
    comment           varchar,
    created_at        timestamp,
    updated_at        timestamp,
    created_by        varchar(100),
    updated_by        varchar(100)
)
