create table products
(
    id         int primary key generated by default as identity,
    name       varchar(100) unique,
    type       varchar(20),
    quantity   int,
    created_at date,
    updated_at timestamp

);

create table product_orders
(
    id         int primary key generated by default as identity,
    product_id int references products (id),
    order_id   int,
    created_at timestamp,
    updated_at timestamp
)