version: '3'
services:
  bank-db:
    image: postgres:12
    restart: always
    ports:
      - 5445:5432
    environment:
      POSTGRES_PASSWORD : pass
      POSTGRES_USER : bank
      POSTGRES_DB : bankDB