version: '3'
services:
  client-db:
    image: postgres:12
    restart: always
    ports:
      - 5444:5432
    environment:
      POSTGRES_PASSWORD : pass
      POSTGRES_USER : client
      POSTGRES_DB : clientDB