version: '3'
services:
  order-db:
    image: postgres:12
    restart: always
    ports:
      - 5447:5432
    environment:
      POSTGRES_PASSWORD : pass
      POSTGRES_USER : inventory
      POSTGRES_DB : inventoryDB